### ISSUE TITLE
Wrong production URL inside master branch

### ISSUE THREAD

**Issue by tivjres** [zsea-group/kindler-win#1]
Here
https://github.com/zsea-group/kindler-win/commit/f55cf19c6914f890f36d38dc261bf8572fcfd0fc#diff-289397c31539bdb0ef59853296c3ddaeR11

is stored wrong url, was used just for test.

It's okay?

**Comment by SiddyBass** [comment]
> 
> 
> Here
> [f55cf19#diff-289397c31539bdb0ef59853296c3ddaeR11](https://github.com/zsea-group/kindler-win/commit/f55cf19c6914f890f36d38dc261bf8572fcfd0fc#diff-289397c31539bdb0ef59853296c3ddaeR11)
> 
> is stored wrong url, was used just for test.
> 
> It's okay?

Yes. It's okay. Because we haven't dev api server. So dev means test. Url can be changed here.
