### ISSUE TITLE
Strange behavior on login view

### ISSUE THREAD

**Issue by SiddyBass** [zsea-group/kindler-win#3]
I saw, that login view have strange default inputed value. Is it correct?

**Comment by kcmame** [comment]
It is a feature) It isn`t fun to input login every time.

**Comment by SiddyBass** [comment]
Login can be stored on device (last inputted value) instead default value in input. Maybe would be better to change it?

**Comment by SiddyBass** [comment]
I insist that you delete it!

**Comment by kcmame** [comment]
Done
