### ISSUE TITLE
Exception after load chat list, when resize or scroll window

### ISSUE THREAD

**Issue by kcmame** [zsea-group/kindler-win#6]
System.Windows.Markup.XamlParseException: 'Необходимо создать DependencySource в том же потоке, в котором создан DependencyObject.'
ArgumentException: Необходимо создать DependencySource в том же потоке, в котором создан DependencyObject.

**Comment by SiddyBass** [comment]
As I can see, that you attempt to create ObservableCollection & RowItem in worker thread through Task. The transfer of image loading into worker thread but keep these objects creation in main thread can solve your issue.

**Comment by SiddyBass** [comment]
I'm closing this issue, because the solution above should work.
